version: "3"

services:
  scraper:
   build: ./
   command: poetry run python main.py
   container_name: reddit_vk_scraper
   env_file:
     - .env
   logging:
     driver: "json-file"
     options:
       max-size: "10m"